export enum CustomSport {
    Badminton = 1,
    Basketball,
    Darts,
    ESports,
    Hockey,
    Korfball,
    Chess,
    Squash,
    TableTennis,
    Tennis,
    Football,
    Volleyball,
    Baseball,
    IceHockey,
    Shuffleboard,
    Jass,
    BadmintonDouble,
    SquashDouble,
    TennisDouble,
    TableTennisDouble,
}
